apiVersion: apps/v1
kind: Deployment
metadata:
  name: service_name
  labels:
    app: service_name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service_name
  template:
    metadata:
      labels:
        app: service_name
    spec:
      volumes:
        - name: workspace-volume
          emptyDir: {}
      initContainers:
        - name: copy-s3-resources
          image: amazon/aws-cli
          command: ["/bin/sh", "-c"]
          args:
            - >
              aws s3 cp s3://code-now/projects/service_name/ /workspace/ --recursive &&
              echo "Resources copied from S3";
          env:
            - name: AWS_ACCESS_KEY_ID
              value: *****
            - name: AWS_SECRET_ACCESS_KEY
              value: *****
          volumeMounts:
            - name: workspace-volume
              mountPath: /workspace
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
      containers:
        - name: runner
          image: pragadeesh97/code-it:latest
          ports:
            - containerPort: 3001
            - containerPort: 3000
          env:
            - name: COPY_DIRECTORY_PATH
              value: "../workspace"
          volumeMounts:
            - name: workspace-volume
              mountPath: /workspace

---
apiVersion: v1
kind: Service
metadata:
  name: service_name
spec:
  selector:
    app: service_name
  ports:
    - protocol: TCP
      name: ws
      port: 3001
      targetPort: 3001
    - protocol: TCP
      name: user
      port: 3000
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1 # specifies that this is an ingress resource in Kubernetes
kind: Ingress
metadata:
  name: service_name
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: service_name.pragadeesh97.com
      http:
        paths:
          - path: /output
            pathType: Prefix
            backend:
              service:
                name: service_name
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service_name
                port:
                  number: 3001
